//export const RESULTS_HAS_ERRORED = 'RESULTS_HAS_ERRORED';
//export const RESULTS_IS_LOADING = 'RESULTS_IS_LOADING';
//export const RESULTS_FETCH_DATA_SUCCESS = 'RESULTS_FETCH_DATA_SUCCESS';

export const SET_SCOUT_PARTICIPATE = 'SET_SCOUT_PARTICIPATE';

export const SET_RIDE_ROLE = 'SET_RIDE_ROLE';
export const SET_RIDES = 'SET_RIDES';
