//export const RESULTS_HAS_ERRORED = 'RESULTS_HAS_ERRORED';
//export const RESULTS_IS_LOADING = 'RESULTS_IS_LOADING';
//export const RESULTS_FETCH_DATA_SUCCESS = 'RESULTS_FETCH_DATA_SUCCESS';

export const SET_SCOUT_PARTICIPATE = 'SET_SCOUT_PARTICIPATE';

export const SET_RIDE_ROLE = 'SET_RIDE_ROLE';
export const SET_RIDES = 'SET_RIDES';

export const INVITATION_IS_LOADING = 'INVITATION_IS_LOADING';
export const INVITATION_HAS_ERRORED = 'INVITATION_HAS_ERRORED';
export const INVITATION_FETCH_DATA_SUCCESS = 'INVITATION_FETCH_DATA_SUCCESS';

export const ACCOUNT_IS_LOADING = 'ACCOUNT_IS_LOADING';
export const ACCOUNT_HAS_ERRORED = 'ACCOUNT_HAS_ERRORED';
export const ACCOUNT_FETCH_DATA_SUCCESS = 'ACCOUNT_FETCH_DATA_SUCCESS';
